# MaidSafe CI script - 20150228
#
language: cpp
compiler:
- gcc
os:
- linux
git:
    submodules: false
before_install:
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive
- git checkout next
- git submodule foreach git checkout next
install:
- sudo pip install cpp-coveralls
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
#- sudo add-apt-repository -y ppa:afrank/boost was for libboost1.57-all-dev mlocate
- sudo apt-get clean
- sudo apt-get update
- sudo apt-get install -y -f build-essential python-psutil libfuse-dev libicu-dev valgrind binutils-gold gcc-4.9 g++-4.9 python-dev
#- sudo updatedb
#- sudo locate libboost | grep /lib | grep -e ".a$"
- wget http://www.cmake.org/files/v2.8/cmake-2.8.12.2.tar.gz
- tar xf cmake-2.8.12.2.tar.gz
- cd cmake-2.8.12.2
- ./bootstrap
- make
- sudo make install
before_script:
- cd ..
- cmake -H. -Bbuild_maidsafe -DCMAKE_BUILD_TYPE=Debug -DCOVERAGE=On -DCMAKE_CXX_COMPILER=g++-4.9 -DCMAKE_C_COMPILER=gcc-4.9
- cd build_maidsafe
script:
- ./configure --enable-gcov && make && make check
- make AllCommon
after_success:
- coveralls --exclude lib --exclude tests --gcov-options '\-lp' 
